#!/usr/bin/env bash
# Install nginx on your web-01 server
sudo apt-get update
sudo apt install nginx -y
sudo service nginx status
sudo ufw allow 'Nginx Full'
echo "Hello World!" > /var/www/html/index.html
sudo nginx -t
sudo nginx -s reload