#!/usr/bin/env bash
# Install nginx on your web-01 server
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx Full'
echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart 