#!/usr/bin/env bash
#Create a MySQL backup

if [ "$#" -ne 1 ]; then
    echo "Usage: 5-mysql_backup PASSWORD"
    exit 0
fi


mysqldump -u root -p"$1" --all-databases > "backup.sql"

tar -czvf "$(date '+%d-%m-%Y').tar.gz" "backup.sql"
