#!/usr/bin/env bash
#a bash script that displays To infinity..., sleep 2, i am invisible - when receiving a SIGTERM signal
trap "echo I am invincible!!!" SIGTERM
while true
do 
	echo "To infinity and beyond"
	sleep 2
done
