#!/usr/bin/env bash
#a Bash script that displays numbers from 1 to 100.
for i in {1..100}
do
	if (( i % 15 == 0 ));
	then
		echo "FizzBuzz"
	elif (( i % 3 == 0 ));
	then
		echo "Fizz"
	else
		echo "$i"
	fi
done
