#!/usr/bin/env bash
# a Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.

file_name="/etc/passwd"

while IFS=: read -r USERNAME GROUP_ID COMMAND_SHELL HOME_DIRECTORY USER_ID USER_ID_INFO PASSWORD
do
echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND_SHELL. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER_ID_INFO"
done < $file_name