#!/usr/bin/env bash
#a Bash script that displays:
#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed (refer to the example)
for content in *
do
	echo "$content" | cut -d "-" -f2
done
