#!/usr/bin/env bash
#a Bash script that configures an Ubuntu server with the below requirements.
#Requirements: localhost resolves to 127.0.0.2, facebook.com resolves to 8.8.8.8., The checker is running on Docker,

HOST="localhost"
LOOCALHOST="127.0.0.2"

cp /etc/hosts ~/hosts.new
sed -i "/$HOST/ s/.*/$LOOCALHOST\t$HOST/g" ~/hosts.new
sed -i "/$HOST$/a 8.8.8.8\t\tfacebook.com" ~/hosts.new
cp -f ~/hosts.new /etc/hosts
