#!/usr/bin/env bash
# a script that configures the container with nginx user, port 8080
sudo chown 777 /etc/nginx/nginx.conf
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill -f apache2
sudo -u nginx service nginx restart
