#!/usr/bin/env bash
# Using what you did for task #1, make your fix short and sweet.
chmod 777 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill -9 apache2
su nginx -c "service nginx restart"
